sudo: enabled
services:
- docker
script:
- docker build -t quay.io/easauceda/writing-prompts-digest:${TRAVIS_COMMIT} .
deploy:
  provider: script
  script:
  - docker login -u=${QUAY_USERNAME} -p=${QUAY_PW} quay.io
  - docker push -t quay.io/easauceda/writing-prompts-digest:${TRAVIS_COMMIT}
env:
  global:
  - secure: lUPETpEE+rYMQ0jVRjcYlW3Av6W8+TcBK6CS3j/0uconHnpkdZ1W2qZHGTrq3zBKknf/lDlJm44ndZPF0byYj/ra62fBcIRHczhbcg8aj6HqCLImEIgrqKN2P26bsjYZ07EMJIoeUF4zuAId7k3cZT8evSOTWrMe49PxMaVZYtT7g/s1nNiG7Shr6OCHEcH7q110o7iX9/YVipKeAETTiQ60n51UaBWMISAvmFU6grj/+5LyuoQ7CIdht1Y2j6lnPSGsISDHN2gjqaQl34nyXXsKO455I7Rf7D+MDfmTNmQ+xWqM2M0F8Dv5ZlISaWp7VVsJHgoWM3wrkDI4HQ8MkE8iXVhXaUnvn7JlVeNz2B5ERUDCZ8RouC9U11rUxT2yGNrGLTFCB1AQ6AnYZ8TKKBdTqUcPG3XrpKGSJhRBsP3wfiPC8LscaIv7KQfW64mYXhsfizxhh5Gvcn0tx4gYEZiw/pRdpQmRT8U7snaoWdd3DCQwE/OUVSDkGUYEEt8KBkQZDPuK9A7qgOlFyYWwLLMQh/YIa33s9a0rgkslorNUSuUT0cbw0ug3hRJ4w9lroZdW9LWSuk0Gw0TE9Nn01pADS0XwVWCc+tN7btR05sK9p/TQML7w8pQCujULDTbMIUlh8e+tiMgIyKa4SbIdDseJPxskDvxkf4H4/dwx5GI=
  - secure: tmK15v4byoKwBTqdsiRl6sCaqMCviY2bgzOEOrXx5RxiE8GfHbBN2FvsvY0hUOIpTKpGn8n1Znj2maOg0xXCuANKH4YuF5tx892vXbAVkLxvuQUZkO/BZleKpk8Jp+Uy5axgtvkfn2q1yHJH6r+k6v7tQqd3UGhvzsOXfgRwHNDOW9hhRAljo/6bMNfbGRH9wrDO5oVgzGxGsaYa48oER/COVLeZFeT4NxYKgEJejeHa8GlQpy9+hlqwxZbKbnKBPSGa35xM4iFte7I2xk9gM1rD1D5ZFMksrauhrA3SVkfLtxi2Vh6i6vHeJLvPhmtUL6JABamxwNr/s7CFE4VS2zHMXiiSkfgldpqtIZv8zX6fpR2jsi0qEh+V7jr3ye9/Q9LrX8evDwQ00rmddHXC1tEwLorwfvQ3KOWMOv2FZ2NwWi8FAEK6kQKzyFRj/qEmzOAS/zmouiEusjDvDG4d7CnjVepHNns86fzys9rlQO65Z5UhbYy4Wvl+sSp4G6B3/as9XttUYaV1mRCv+EcoULGp+FXyhRI2URGPvLfelnjNMLo0EatN4hB/TF9Sjrsl10FMTHzpIXp0OvYDgJuLc37jqFOulPdY0KoF/NNCvIcJN3fLvNMVcm142bz/hIsf0WXvBuw5iJpb85o6O6dUXUD1UrXCmAPsYUb37OsipSg=
